import Link from "next/link";
import { notFound } from "next/navigation";
import { PageHeader } from "@/components/page-header";
import { formatCurrency } from "@/lib/format";
import { prisma } from "@/lib/prisma";
import { addItem, approveSettlement, removeItem, saveDraft, saveItemQuantity } from "@/modules/contractor-settlements/actions";
import { eligibleQuantity, settledQuantity, settlementStatusLabel, settlementTotal, subtotal } from "@/modules/contractor-settlements/domain";

export default async function Page({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params;
  const settlement = await prisma.contractorSettlement.findUnique({ where: { id }, include: { contractor: true, items: { include: { outsourcedService: { include: { service: true, productionOrder: { include: { customer: true } }, settlementItems: { include: { settlement: true } } } } } } } });
  if (!settlement) notFound();
  const [contractors, candidates] = settlement.status === "DRAFT" ? await Promise.all([
    prisma.contractor.findMany({ where: { active: true }, orderBy: { name: "asc" } }),
    prisma.outsourcedService.findMany({ where: { contractorId: settlement.contractorId, approvedQuantity: { gt: 0 }, id: { notIn: settlement.items.map((item) => item.outsourcedServiceId) } }, include: { service: true, productionOrder: { include: { customer: true } }, settlementItems: { include: { settlement: true } } }, orderBy: { createdAt: "desc" } }),
  ]) : [[], []];
  const pieces = settlement.items.reduce((sum, item) => sum + item.approvedQuantityIncluded, 0);
  const total = settlementTotal(settlement.items.map((item) => ({ quantity: item.approvedQuantityIncluded, price: item.appliedUnitPriceSnapshot })));
  const uniqueOrders = new Set(settlement.items.map((item) => item.outsourcedService.productionOrderId)).size;
  const eligibleCandidates = candidates.map((item) => { const closed = settledQuantity(item.settlementItems); return { ...item, closed, eligible: eligibleQuantity(item.approvedQuantity, closed) }; }).filter((item) => item.eligible > 0);

  return <><PageHeader title="Detalhe do fechamento" description={settlement.status === "DRAFT" ? "Rascunho editável. O saldo definitivo é validado somente na aprovação." : "Fechamento aprovado e disponível somente para consulta."} action={{ label: "Voltar aos Fechamentos", href: "/terceirizacao/fechamentos" }}/><section className="panel mb-5"><dl className="detail-grid"><div><dt>Terceirizado</dt><dd>{settlement.contractor.name}</dd></div><div><dt>Competência</dt><dd>{String(settlement.periodMonth).padStart(2, "0")}/{settlement.periodYear}</dd></div><div><dt>Status</dt><dd><span className={settlement.status === "APPROVED" ? "status-active" : "status-inactive"}>{settlementStatusLabel(settlement.status)}</span></dd></div><div><dt>Criado em</dt><dd>{settlement.createdAt.toLocaleString("pt-BR")}</dd></div><div><dt>Aprovado em</dt><dd>{settlement.approvedAt?.toLocaleString("pt-BR") ?? "—"}</dd></div><div><dt>Observações</dt><dd>{settlement.notes || "—"}</dd></div></dl></section>
  {settlement.status === "DRAFT" ? <section className="panel mb-5"><h2 className="section-title mb-4">Editar rascunho</h2><form action={saveDraft} className="form-grid"><input name="id" type="hidden" value={id}/><label className="field">Mês<input defaultValue={settlement.periodMonth} max={12} min={1} name="periodMonth" required type="number"/></label><label className="field">Ano<input defaultValue={settlement.periodYear} name="periodYear" required type="number"/></label><label className="field">Terceirizado<select defaultValue={settlement.contractorId} disabled={settlement.items.length > 0} name="contractorId">{contractors.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select>{settlement.items.length > 0 ? <><input name="contractorId" type="hidden" value={settlement.contractorId}/><small>Remova os itens antes de alterar o terceirizado.</small></> : null}</label><label className="field sm:col-span-2">Observações<textarea defaultValue={settlement.notes ?? ""} name="notes" rows={3}/></label><div className="flex items-end"><button className="button-primary">Salvar edição</button></div></form></section> : null}
  <section className="panel mb-5"><div className="mb-4 flex flex-wrap items-center justify-between gap-3"><h2 className="section-title">Itens</h2><Link className="button-secondary" href={`/terceirizacao/fechamentos/${id}/demonstrativo`}>Demonstrativo</Link></div>{!settlement.items.length ? <p className="empty-state">Nenhum item adicionado.</p> : <div className="table-wrap"><table><thead><tr><th>OP</th><th>Cliente</th><th>Serviço</th><th>Quantidade</th><th>Elegível</th><th>Preço snapshot</th><th>Subtotal</th>{settlement.status === "DRAFT" ? <th>Ações</th> : null}</tr></thead><tbody>{settlement.items.map((item) => { const closed = settledQuantity(item.outsourcedService.settlementItems); const eligible = eligibleQuantity(item.outsourcedService.approvedQuantity, closed); return <tr key={item.id}><td>{item.outsourcedService.productionOrder.number}</td><td>{item.outsourcedService.productionOrder.customer.name}</td><td>{item.outsourcedService.service.name}</td><td>{settlement.status === "DRAFT" ? <form action={saveItemQuantity} className="flex gap-2"><input name="settlementId" type="hidden" value={id}/><input name="itemId" type="hidden" value={item.id}/><input className="w-24 rounded border p-2" defaultValue={item.approvedQuantityIncluded} max={eligible} min={1} name="quantity" required type="number"/><button className="button-secondary">Salvar</button></form> : item.approvedQuantityIncluded.toLocaleString("pt-BR")}</td><td>{eligible.toLocaleString("pt-BR")}</td><td>{formatCurrency(item.appliedUnitPriceSnapshot)}</td><td>{formatCurrency(subtotal(item.approvedQuantityIncluded, item.appliedUnitPriceSnapshot))}</td>{settlement.status === "DRAFT" ? <td><form action={removeItem}><input name="settlementId" type="hidden" value={id}/><input name="itemId" type="hidden" value={item.id}/><button className="link-button">Remover</button></form></td> : null}</tr>; })}</tbody><tfoot><tr><th colSpan={3}>Resumo: {uniqueOrders} OP(s)</th><th>{pieces.toLocaleString("pt-BR")}</th><th/><th>Total</th><th>{formatCurrency(total)}</th>{settlement.status === "DRAFT" ? <th/> : null}</tr></tfoot></table></div>}</section>
  {settlement.status === "DRAFT" ? <><section className="panel mb-5"><h2 className="section-title mb-2">Adicionar item</h2><p className="mb-4 text-sm text-slate-600">Rascunhos não reservam saldo. A disponibilidade definitiva será conferida na aprovação.</p>{!eligibleCandidates.length ? <p className="empty-state">Nenhum serviço elegível para este terceirizado.</p> : <form action={addItem} className="form-grid"><input name="id" type="hidden" value={id}/><label className="field sm:col-span-2">Serviço terceirizado<select name="outsourcedServiceId" required><option value="">Selecione</option>{eligibleCandidates.map((item) => <option key={item.id} value={item.id}>OP {item.productionOrder.number} · {item.productionOrder.customer.name} · {item.service.name} · aprovada {item.approvedQuantity} · fechada {item.closed} · elegível {item.eligible} · {formatCurrency(item.appliedUnitPrice)} · disponível {formatCurrency(subtotal(item.eligible, item.appliedUnitPrice))}</option>)}</select></label><label className="field">Quantidade a incluir<input min={1} name="quantity" required type="number"/></label><div className="flex items-end"><button className="button-primary">Adicionar item</button></div></form>}</section><section className="panel"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="section-title">Aprovar fechamento</h2><p className="text-sm text-slate-600">A aprovação é explícita, consome o saldo e torna o fechamento imutável.</p></div><form action={approveSettlement}><input name="id" type="hidden" value={id}/><button className="button-primary" disabled={!settlement.items.length}>Aprovar fechamento</button></form></div></section></> : null}</>;
}
