import Link from "next/link";
import { notFound } from "next/navigation";
import { OutsourcingFlowNav } from "@/components/outsourcing-flow-nav";
import { PageHeader } from "@/components/page-header";
import { Button } from "@/components/ui/button";
import { StatCard } from "@/components/ui/stat-card";
import { StatusChip } from "@/components/ui/status-chip";
import { formatCurrency } from "@/lib/format";
import { prisma } from "@/lib/prisma";
import { addItem, approveSettlement, removeItem, saveDraft, saveItemQuantity } from "@/modules/contractor-settlements/actions";
import { eligibleQuantity, settledQuantity, settlementStatusLabel, settlementTotal, subtotal } from "@/modules/contractor-settlements/domain";

export default async function Page({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params;
  const settlement = await prisma.contractorSettlement.findUnique({ where: { id }, include: { company: true, contractor: true, accountPayable: true, items: { include: { outsourcedService: { include: { service: true, productionOrder: { include: { customer: true } }, settlementItems: { include: { settlement: true } } } } } } } });
  if (!settlement) notFound();
  const [contractors, companies, candidates] = settlement.status === "DRAFT" ? await Promise.all([
    prisma.contractor.findMany({ where: { active: true }, orderBy: { name: "asc" } }),
    prisma.company.findMany({ where: { active: true }, orderBy: { name: "asc" } }),
    prisma.outsourcedService.findMany({ where: { contractorId: settlement.contractorId, productionOrder: { companyId: settlement.companyId }, approvedQuantity: { gt: 0 }, id: { notIn: settlement.items.map((item) => item.outsourcedServiceId) } }, include: { service: true, productionOrder: { include: { customer: true } }, settlementItems: { include: { settlement: true } } }, orderBy: { createdAt: "desc" } }),
  ]) : [[], [], []];
  const pieces = settlement.items.reduce((sum, item) => sum + item.approvedQuantityIncluded, 0);
  const total = settlementTotal(settlement.items.map((item) => ({ quantity: item.approvedQuantityIncluded, price: item.appliedUnitPriceSnapshot })));
  const eligibleCandidates = candidates.map((item) => { const closed = settledQuantity(item.settlementItems); return { ...item, closed, eligible: eligibleQuantity(item.approvedQuantity, closed) }; }).filter((item) => item.eligible > 0);
  return <><PageHeader title={`${settlement.contractor.name} • ${String(settlement.periodMonth).padStart(2, "0")}/${settlement.periodYear}`} description={settlement.status === "DRAFT" ? "Rascunho editável e restrito a uma empresa." : "Fechamento aprovado e imutável."} action={{ label: "Voltar", href: "/terceirizacao/fechamentos" }}/>
    <OutsourcingFlowNav active="settlements"/>
    <section className="outsourcing-stat-grid"><StatCard label="Status" value={settlementStatusLabel(settlement.status)} helper={settlement.accountPayable ? "Conta a pagar gerada" : "Sem A/P gerada"} variant={settlement.status === "APPROVED" ? "success" : "neutral"}/><StatCard label="Valor total" value={formatCurrency(total)} helper={`${pieces.toLocaleString("pt-BR")} peças`} variant="info"/><StatCard label="Itens" value={settlement.items.length} helper={`${new Set(settlement.items.map((item) => item.outsourcedService.productionOrderId)).size} OP(s)`}/></section>
    <section className="panel mb-5"><dl className="detail-grid"><div><dt>Empresa</dt><dd>{settlement.company.tradeName || settlement.company.name}</dd></div><div><dt>Terceirizado</dt><dd>{settlement.contractor.name}</dd></div><div><dt>Competência</dt><dd>{String(settlement.periodMonth).padStart(2, "0")}/{settlement.periodYear}</dd></div><div><dt>Status</dt><dd><StatusChip variant={settlement.status === "APPROVED" ? "success" : "neutral"}>{settlementStatusLabel(settlement.status)}</StatusChip></dd></div><div><dt>Aprovado em</dt><dd>{settlement.approvedAt?.toLocaleString("pt-BR") ?? "—"}</dd></div><div><dt>A/P associada</dt><dd>{settlement.accountPayable ? "Gerada" : "—"}</dd></div><div className="sm:col-span-2"><dt>Observações</dt><dd>{settlement.notes || "—"}</dd></div></dl></section>
    {settlement.status === "DRAFT" ? <section className="panel mb-5"><h2 className="section-title mb-4">Editar rascunho</h2><form action={saveDraft} className="form-grid"><input name="id" type="hidden" value={id}/><label className="field">Empresa<select defaultValue={settlement.companyId} disabled={settlement.items.length > 0} name="companyId">{companies.map((item) => <option key={item.id} value={item.id}>{item.tradeName || item.name}</option>)}</select>{settlement.items.length ? <><input name="companyId" type="hidden" value={settlement.companyId}/><small>Remova os itens antes de alterar a empresa.</small></> : null}</label><label className="field">Terceirizado<select defaultValue={settlement.contractorId} disabled={settlement.items.length > 0} name="contractorId">{contractors.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select>{settlement.items.length ? <input name="contractorId" type="hidden" value={settlement.contractorId}/> : null}</label><label className="field">Mês<input defaultValue={settlement.periodMonth} max={12} min={1} name="periodMonth" type="number"/></label><label className="field">Ano<input defaultValue={settlement.periodYear} name="periodYear" type="number"/></label><label className="field">Observações<textarea defaultValue={settlement.notes ?? ""} name="notes"/></label><button className="button-primary">Salvar</button></form></section> : null}
    <section className="panel mb-5"><div className="mb-4 flex flex-wrap items-center justify-between gap-3"><h2 className="section-title">Itens do fechamento</h2><Button href={`/terceirizacao/fechamentos/${id}/demonstrativo`} variant="secondary">Ver demonstrativo</Button></div>
      <div className="outsourcing-card-list">{settlement.items.map((item) => <article className="outsourcing-card" key={item.id}><div className="outsourcing-card-head"><div><strong>OP {item.outsourcedService.productionOrder.number}</strong><p>{item.outsourcedService.productionOrder.customer.name}</p></div><span className="status-info">{formatCurrency(subtotal(item.approvedQuantityIncluded, item.appliedUnitPriceSnapshot))}</span></div><p className="outsourcing-card-title">{item.outsourcedService.service.name}</p><dl className="outsourcing-facts"><div><dt>Quantidade</dt><dd>{item.approvedQuantityIncluded.toLocaleString("pt-BR")}</dd></div><div><dt>Preço aplicado</dt><dd>{formatCurrency(item.appliedUnitPriceSnapshot)}</dd></div></dl>{settlement.status === "DRAFT" ? <div className="settlement-card-actions"><form action={saveItemQuantity} className="flex flex-wrap gap-2"><input name="settlementId" type="hidden" value={id}/><input name="itemId" type="hidden" value={item.id}/><input className="w-24 rounded border p-2" defaultValue={item.approvedQuantityIncluded} min={1} name="quantity" type="number"/><button className="button-secondary">Salvar qtd.</button></form><form action={removeItem}><input name="settlementId" type="hidden" value={id}/><input name="itemId" type="hidden" value={item.id}/><button className="link-button">Remover</button></form></div> : null}</article>)}</div>
      <div className="outsourcing-table-desktop table-wrap"><table><thead><tr><th>OP</th><th>Cliente</th><th>Serviço</th><th>Quantidade</th><th>Preço aplicado</th><th>Subtotal</th><th/></tr></thead><tbody>{settlement.items.map((item) => <tr key={item.id}><td>{item.outsourcedService.productionOrder.number}</td><td>{item.outsourcedService.productionOrder.customer.name}</td><td>{item.outsourcedService.service.name}</td><td>{settlement.status === "DRAFT" ? <form action={saveItemQuantity} className="flex gap-2"><input name="settlementId" type="hidden" value={id}/><input name="itemId" type="hidden" value={item.id}/><input className="w-24 rounded border p-2" defaultValue={item.approvedQuantityIncluded} min={1} name="quantity" type="number"/><button className="button-secondary">Salvar</button></form> : item.approvedQuantityIncluded}</td><td>{formatCurrency(item.appliedUnitPriceSnapshot)}</td><td>{formatCurrency(subtotal(item.approvedQuantityIncluded, item.appliedUnitPriceSnapshot))}</td><td>{settlement.status === "DRAFT" ? <form action={removeItem}><input name="settlementId" type="hidden" value={id}/><input name="itemId" type="hidden" value={item.id}/><button className="link-button">Remover</button></form> : null}</td></tr>)}</tbody></table></div><p className="mt-4 font-semibold">Peças: {pieces.toLocaleString("pt-BR")} · Total: {formatCurrency(total)}</p></section>
    {settlement.status === "DRAFT" ? <><section className="panel mb-5"><h2 className="section-title mb-3">Serviços disponíveis para fechamento</h2>{eligibleCandidates.length ? <form action={addItem} className="form-grid"><input name="id" type="hidden" value={id}/><label className="field sm:col-span-2">Serviço<select name="outsourcedServiceId" required><option value="">Selecione</option>{eligibleCandidates.map((item) => <option key={item.id} value={item.id}>OP {item.productionOrder.number} · {item.service.name} · disponível para fechamento {item.eligible}</option>)}</select></label><label className="field">Quantidade<input min={1} name="quantity" required type="number"/></label><button className="button-primary">Adicionar item</button></form> : <p className="empty-state">Nenhum serviço elegível.</p>}</section><form action={approveSettlement} className="panel settlement-action-panel"><input name="id" type="hidden" value={id}/><div><h2 className="section-title">Aprovar fechamento</h2><p>Depois de aprovado, o fechamento fica imutável e poderá gerar Conta a Pagar.</p></div><button className="button-primary" disabled={!settlement.items.length}>Aprovar fechamento</button></form></> : <section className="panel settlement-action-panel"><div><h2 className="section-title">Conta a pagar</h2><p>{settlement.accountPayable ? "Obrigação financeira já criada para este fechamento." : "Gere a Conta a Pagar a partir do fechamento aprovado."}</p></div>{settlement.accountPayable ? <Link className="button-primary" href={`/financeiro/contas-a-pagar/${settlement.accountPayable.id}`}>Ver Conta a Pagar</Link> : <Link className="button-primary" href={`/terceirizacao/fechamentos/${id}/conta-a-pagar`}>Gerar Conta a Pagar</Link>}</section>}
  </>;
}
