import Link from "next/link";
import { PageHeader } from "@/components/page-header";
import { prisma } from "@/lib/prisma";
import { derivedQuantities, operationalStatus } from "@/modules/outsourcing/domain";

type Params = { q?: string; contractorId?: string; serviceId?: string };
export default async function Page({ searchParams }: { searchParams: Promise<Params> }) {
  const params = await searchParams;
  const [items, contractors, services] = await Promise.all([
    prisma.outsourcedService.findMany({ where: { productionOrder: { number: params.q ? { contains: params.q, mode: "insensitive" } : undefined }, contractorId: params.contractorId || undefined, serviceId: params.serviceId || undefined }, include: { contractor: true, service: true, deliveryNoteItems: { select: { quantity: true } }, returns: { select: { quantity: true } }, productionOrder: { include: { customer: true } } }, orderBy: { createdAt: "desc" } }),
    prisma.contractor.findMany({ orderBy: { name: "asc" } }), prisma.service.findMany({ orderBy: { name: "asc" } }),
  ]);
  return <><PageHeader title="Terceirização" description="Visão operacional dos serviços externos e suas movimentações."/><form className="panel mb-5 form-grid"><label className="field">OP<input defaultValue={params.q} name="q"/></label><label className="field">Terceirizado<select defaultValue={params.contractorId ?? ""} name="contractorId"><option value="">Todos</option>{contractors.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label className="field">Serviço<select defaultValue={params.serviceId ?? ""} name="serviceId"><option value="">Todos</option>{services.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><div className="flex items-end gap-2"><button className="button-primary">Filtrar</button><Link className="button-secondary" href="/terceirizacao">Limpar</Link></div></form><section className="panel">{!items.length ? <p className="empty-state">Nenhum serviço terceirizado encontrado.</p> : <div className="table-wrap"><table><thead><tr><th>OP</th><th>Cliente</th><th>Serviço</th><th>Terceirizado</th><th>Prevista</th><th>Enviada</th><th>Retornada</th><th>Pendente</th><th>Situação</th></tr></thead><tbody>{items.map((item) => { const quantities = derivedQuantities(item.deliveryNoteItems, item.returns); return <tr key={item.id}><td><Link className="link-button" href={`/ops/${item.productionOrderId}`}>{item.productionOrder.number}</Link></td><td>{item.productionOrder.customer.name}</td><td>{item.service.name}</td><td>{item.contractor.name}</td><td>{item.plannedQuantity?.toLocaleString("pt-BR") ?? "—"}</td><td>{quantities.sentQuantity.toLocaleString("pt-BR")}</td><td>{quantities.returnedQuantity.toLocaleString("pt-BR")}</td><td>{quantities.pendingQuantity.toLocaleString("pt-BR")}</td><td>{operationalStatus(quantities.sentQuantity, quantities.returnedQuantity)}</td></tr>; })}</tbody></table></div>}</section></>;
}
