import Link from "next/link";
import { notFound } from "next/navigation";
import { Feedback } from "@/components/feedback";
import { PageHeader } from "@/components/page-header";
import { formatCurrency, formatDate } from "@/lib/format";
import { prisma } from "@/lib/prisma";
import { financialStatus, paidAmount, remainingAmount } from "@/modules/accounts-payable/domain";
export default async function Page({ params, searchParams }: { params: Promise<{ id: string }>; searchParams: Promise<{ success?: string; error?: string }> }) {
  const { id } = await params;
  const [a, messages] = await Promise.all([prisma.accountPayable.findUnique({ where: { id }, include: { company: true, payments: { orderBy: [{ paymentDate: "desc" }, { createdAt: "desc" }] }, contractorSettlement: { include: { contractor: true } } } }), searchParams]);
  if (!a) notFound();
  const paid = paidAmount(a.payments), remaining = remainingAmount(a.originalAmount, a.payments), status = financialStatus(a.originalAmount, a.dueDate, a.payments);
  return <><PageHeader title="Conta a Pagar" description="Fechamento, obrigação e pagamento são fatos distintos." action={{ label: "Voltar às contas", href: "/financeiro/contas-a-pagar" }}/><Feedback {...messages}/><section className="panel mb-5"><dl className="detail-grid"><div><dt>Empresa</dt><dd>{a.company.tradeName || a.company.name}</dd></div><div><dt>Descrição</dt><dd>{a.description}</dd></div><div><dt>Origem</dt><dd><Link className="link-button" href={`/terceirizacao/fechamentos/${a.contractorSettlementId}`}>Fechamento de Terceirizados</Link></dd></div><div><dt>Terceirizado</dt><dd>{a.contractorSettlement.contractor.name}</dd></div><div><dt>Competência</dt><dd>{formatDate(a.competenceDate)}</dd></div><div><dt>Vencimento</dt><dd>{formatDate(a.dueDate)}</dd></div><div><dt>Valor original</dt><dd>{formatCurrency(a.originalAmount)}</dd></div><div><dt>Pago</dt><dd>{formatCurrency(paid)}</dd></div><div><dt>Saldo</dt><dd>{formatCurrency(remaining)}</dd></div><div><dt>Situação</dt><dd>{status}</dd></div></dl></section><section className="panel"><div className="mb-4 flex items-center justify-between"><h2 className="section-title">Pagamentos</h2>{remaining.gt(0) ? <Link className="button-primary" href={`/financeiro/contas-a-pagar/${id}/pagamentos/novo`}>Registrar pagamento</Link> : null}</div>{a.payments.length ? <div className="table-wrap"><table><thead><tr><th>Data</th><th>Valor</th><th>Observações</th><th>Criado em</th></tr></thead><tbody>{a.payments.map(payment => <tr key={payment.id}><td>{formatDate(payment.paymentDate)}</td><td>{formatCurrency(payment.amount)}</td><td>{payment.notes || "—"}</td><td>{payment.createdAt.toLocaleString("pt-BR")}</td></tr>)}</tbody></table></div> : <p className="empty-state">Nenhum pagamento registrado.</p>}</section></>;
}
