"use server";
import { revalidatePath } from "next/cache";
import { z } from "zod";
import { prisma } from "@/lib/prisma";
import { redirectWithMessage } from "@/lib/form";
import { validApproval, validReturn } from "./domain";
const idSchema=z.string().cuid(); const dateSchema=z.string().regex(/^\d{4}-\d{2}-\d{2}$/);
function refresh(id:string){ revalidatePath("/terceirizacao"); revalidatePath("/terceirizacao/cobrancas"); revalidatePath(`/terceirizacao/${id}/retorno`); }
export async function registerReturn(data:FormData){ const id=String(data.get("id")??""); const path=`/terceirizacao/${id}/retorno`; try { idSchema.parse(id); const quantity=z.coerce.number().int().parse(data.get("quantity")); const returnDate=dateSchema.parse(data.get("returnDate")); const notes=String(data.get("notes")??"").trim()||null; await prisma.$transaction(async tx=>{ await tx.$queryRaw`SELECT "id" FROM "OutsourcedService" WHERE "id" = ${id} FOR UPDATE`; const item=await tx.outsourcedService.findUnique({where:{id},include:{deliveryNoteItems:{select:{quantity:true}},returns:{select:{quantity:true}}}}); if(!item) throw new Error("Serviço terceirizado não encontrado."); const sent=item.deliveryNoteItems.reduce((s,x)=>s+x.quantity,0),returned=item.returns.reduce((s,x)=>s+x.quantity,0); if(!validReturn(quantity,sent-returned)) throw new Error("A quantidade deve ser inteira, maior que zero e não pode ultrapassar a pendência."); await tx.outsourcingReturn.create({data:{outsourcedServiceId:id,returnDate:new Date(`${returnDate}T00:00:00.000Z`),quantity,notes}}); }); refresh(id); redirectWithMessage(path,"success","Retorno registrado."); } catch(error){ if(error&&typeof error==="object"&&"digest" in error) throw error; redirectWithMessage(path,"error",error instanceof Error?error.message:"Não foi possível registrar o retorno."); } }
export async function updateApprovedQuantity(data:FormData){ const id=String(data.get("id")??""); const path=`/terceirizacao/${id}/retorno`; try { idSchema.parse(id); const quantity=z.coerce.number().int().parse(data.get("approvedQuantity")); await prisma.$transaction(async tx=>{ await tx.$queryRaw`SELECT "id" FROM "OutsourcedService" WHERE "id" = ${id} FOR UPDATE`; const item=await tx.outsourcedService.findUnique({where:{id},include:{returns:{select:{quantity:true}}}}); if(!item) throw new Error("Serviço terceirizado não encontrado."); const returned=item.returns.reduce((s,x)=>s+x.quantity,0); if(!validApproval(quantity,returned)) throw new Error("A quantidade aprovada deve estar entre zero e o total retornado."); await tx.outsourcedService.update({where:{id},data:{approvedQuantity:quantity}}); }); refresh(id); redirectWithMessage(path,"success","Quantidade aprovada atualizada."); } catch(error){ if(error&&typeof error==="object"&&"digest" in error) throw error; redirectWithMessage(path,"error",error instanceof Error?error.message:"Não foi possível atualizar a aprovação."); } }
