import { notFound } from "next/navigation";
import { Feedback } from "@/components/feedback";
import { PageHeader } from "@/components/page-header";
import { ProductionOrderForm } from "@/components/production-order-form";
import { prisma } from "@/lib/prisma";
import { dateInputValue, formatCurrency, formatDate } from "@/lib/format";
import { updateProductionOrder } from "@/modules/production-orders/actions";
import { getOrderOptions } from "@/modules/production-orders/queries";
import { calculateOrderTotal } from "@/modules/production-orders/validation";

export default async function Page({ params, searchParams }: { params: Promise<{ id: string }>; searchParams: Promise<{ success?: string; error?: string }> }) { const { id } = await params; const [order, messages] = await Promise.all([prisma.productionOrder.findUnique({ where: { id }, include: { company: true, customer: true, product: true } }), searchParams]); if (!order) notFound(); const options = await getOrderOptions(order); return <><PageHeader title={`OP ${order.number}`} description="Dados comerciais e econômicos da ordem de produção." action={{ label: "Voltar às OPs", href: "/ops" }} /><Feedback {...messages} />
  <section className="panel mb-6"><dl className="detail-grid"><div><dt>Data de entrada</dt><dd>{formatDate(order.entryDate)}</dd></div><div><dt>Empresa</dt><dd>{order.company.tradeName || order.company.name}</dd></div><div><dt>Cliente</dt><dd>{order.customer.name}</dd></div><div><dt>Produto / referência</dt><dd>{order.product.name}{order.product.reference ? ` — ${order.product.reference}` : ""}</dd></div><div><dt>Quantidade</dt><dd>{order.quantity.toLocaleString("pt-BR")}</dd></div><div><dt>Preço unitário</dt><dd>{formatCurrency(order.unitPrice)}</dd></div><div><dt>Valor total calculado</dt><dd>{formatCurrency(calculateOrderTotal(order.quantity, order.unitPrice))}</dd></div><div><dt>Criada em</dt><dd>{order.createdAt.toLocaleString("pt-BR")}</dd></div><div><dt>Última atualização</dt><dd>{order.updatedAt.toLocaleString("pt-BR")}</dd></div><div className="sm:col-span-2"><dt>Observações</dt><dd>{order.notes || "—"}</dd></div></dl></section>
  <details className="panel mb-6"><summary className="cursor-pointer font-semibold text-[var(--brand)]">Editar OP</summary><div className="mt-5"><ProductionOrderForm action={updateProductionOrder} {...options} values={{ id: order.id, number: order.number, entryDate: dateInputValue(order.entryDate), companyId: order.companyId, customerId: order.customerId, productId: order.productId, quantity: order.quantity, unitPrice: order.unitPrice.toFixed(4), notes: order.notes }} /></div></details>
  <section className="panel"><div className="flex items-center justify-between"><div><h2 className="section-title">Serviços terceirizados</h2><p className="mt-2 text-sm text-slate-600">Nenhum serviço terceirizado cadastrado para esta OP.</p></div><button className="button-secondary cursor-not-allowed opacity-50" disabled title="Disponível na próxima etapa">Adicionar serviço terceirizado</button></div></section></>; }
