import Link from "next/link";
import { notFound } from "next/navigation";
import { Feedback } from "@/components/feedback";
import { PageHeader } from "@/components/page-header";
import { ProductionOrderForm } from "@/components/production-order-form";
import { prisma } from "@/lib/prisma";
import { dateInputValue, formatCurrency, formatDate } from "@/lib/format";
import { derivedQuantities, operationalStatus, plannedValue } from "@/modules/outsourcing/domain";
import { updateProductionOrder } from "@/modules/production-orders/actions";
import { getOrderOptions } from "@/modules/production-orders/queries";
import { calculateOrderTotal } from "@/modules/production-orders/validation";
import { receivableStatus } from "@/modules/accounts-receivable/domain";

export default async function Page({ params, searchParams }: { params: Promise<{ id: string }>; searchParams: Promise<{ success?: string; error?: string }> }) {
  const { id } = await params; const [order, messages] = await Promise.all([prisma.productionOrder.findUnique({ where: { id }, include: { company: true, customer: true, product: true, billing: { include: { accountReceivable: { include: { allocations: { select: { amount: true } } } } } }, outsourcedServices: { include: { service: true, contractor: true, deliveryNoteItems: { select: { quantity: true } }, returns: { select: { quantity: true } } }, orderBy: { createdAt: "asc" } } } }), searchParams]); if (!order) notFound(); const options = await getOrderOptions(order);
  return <><PageHeader title={`OP ${order.number}`} description="Dados comerciais e econômicos da ordem de produção." action={{ label: "Voltar às OPs", href: "/ops" }}/><Feedback {...messages}/>
    <section className="panel mb-6"><dl className="detail-grid"><div><dt>Data de entrada</dt><dd>{formatDate(order.entryDate)}</dd></div><div><dt>Empresa</dt><dd>{order.company.tradeName || order.company.name}</dd></div><div><dt>Cliente</dt><dd>{order.customer.name}</dd></div><div><dt>Produto / referência</dt><dd>{order.product.name}{order.product.reference ? ` — ${order.product.reference}` : ""}</dd></div><div><dt>Quantidade</dt><dd>{order.quantity.toLocaleString("pt-BR")}</dd></div><div><dt>Preço unitário</dt><dd>{formatCurrency(order.unitPrice)}</dd></div><div><dt>Valor total calculado</dt><dd>{formatCurrency(calculateOrderTotal(order.quantity, order.unitPrice))}</dd></div><div><dt>Criada em</dt><dd>{order.createdAt.toLocaleString("pt-BR")}</dd></div><div><dt>Última atualização</dt><dd>{order.updatedAt.toLocaleString("pt-BR")}</dd></div><div className="sm:col-span-2"><dt>Observações</dt><dd>{order.notes || "—"}</dd></div></dl></section>
    <details className="panel mb-6"><summary className="cursor-pointer font-semibold text-[var(--brand)]">Editar OP</summary><div className="mt-5"><ProductionOrderForm action={updateProductionOrder} {...options} values={{ id: order.id, number: order.number, entryDate: dateInputValue(order.entryDate), companyId: order.companyId, customerId: order.customerId, productId: order.productId, quantity: order.quantity, unitPrice: order.unitPrice.toFixed(4), notes: order.notes }}/></div></details>
    <section className="panel mb-6"><div className="mb-4 flex items-center justify-between"><h2 className="section-title">Faturamento</h2>{!order.billing ? <Link className="button-primary" href={`/ops/${id}/faturamento/novo`}>Registrar faturamento</Link> : null}</div>{order.billing && order.billing.accountReceivable ? <dl className="detail-grid"><div><dt>Nº da NFe</dt><dd>{order.billing.invoiceNumber}</dd></div><div><dt>Emissão</dt><dd>{formatDate(order.billing.issueDate)}</dd></div><div><dt>Competência</dt><dd>{formatDate(order.billing.competenceDate)}</dd></div><div><dt>Valor faturado</dt><dd>{formatCurrency(order.billing.amount)}</dd></div><div><dt>Vencimento</dt><dd>{formatDate(order.billing.accountReceivable.dueDate)}</dd></div><div><dt>Situação</dt><dd>{receivableStatus(order.billing.accountReceivable.originalAmount, order.billing.accountReceivable.dueDate, order.billing.accountReceivable.allocations)}</dd></div><div><dt>Conta a Receber</dt><dd><Link className="link-button" href={`/financeiro/contas-a-receber/${order.billing.accountReceivable.id}`}>Abrir conta</Link></dd></div></dl> : <p className="empty-state">Esta OP ainda não possui faturamento registrado.</p>}</section>
    <section className="panel"><div className="mb-4 flex flex-wrap items-center justify-between gap-3"><div><h2 className="section-title">Serviços terceirizados</h2><p className="mt-1 text-sm text-slate-600">Quantidades e situação são calculadas pelas movimentações existentes.</p></div><Link className="button-primary" href={`/ops/${id}/servicos/novo`}>Adicionar serviço terceirizado</Link></div>
      {!order.outsourcedServices.length ? <p className="empty-state">Nenhum serviço terceirizado cadastrado para esta OP.</p> : <div className="table-wrap"><table><thead><tr><th>Serviço / terceirizado</th><th>Prevista</th><th>Enviada</th><th>Retornada</th><th>Pendente</th><th>Aprovada</th><th>Preço aplicado</th><th>Valor previsto</th><th>Situação</th><th>Ações</th></tr></thead><tbody>{order.outsourcedServices.map(item => { const q = derivedQuantities(item.deliveryNoteItems, item.returns); return <tr key={item.id}><td><strong>{item.service.name}</strong><span className="block text-slate-500">{item.contractor.name}</span></td><td>{item.plannedQuantity?.toLocaleString("pt-BR") ?? "—"}</td><td>{q.sentQuantity.toLocaleString("pt-BR")}</td><td>{q.returnedQuantity.toLocaleString("pt-BR")}</td><td>{q.pendingQuantity.toLocaleString("pt-BR")}</td><td>{item.approvedQuantity.toLocaleString("pt-BR")}</td><td>{formatCurrency(item.appliedUnitPrice)}</td><td>{item.plannedQuantity ? formatCurrency(plannedValue(item.plannedQuantity, item.appliedUnitPrice)) : "—"}</td><td><span className="status-inactive">{operationalStatus(q.sentQuantity, q.returnedQuantity)}</span></td><td><Link className="link-button" href={`/ops/${id}/servicos/${item.id}/editar`}>Editar</Link>{q.sentQuantity > 0 ? <Link className="mt-2 block text-xs font-semibold text-[var(--brand)]" href={`/romaneios?outsourcedServiceId=${item.id}`}>Ver saídas</Link> : null}</td></tr>; })}</tbody></table></div>}
    </section></>;
}
