import { afterAll, beforeAll, describe, expect, it } from "vitest";
import type { PrismaClient } from "@/generated/prisma";
import { createReceipt } from "./creation";
import { receivedAmount, receivableRemainingAmount, receivableStatus } from "@/modules/accounts-receivable/domain";
const run = process.env.RUN_RECEIPT_INTEGRATION === "1", marker = `TEMP QA RECEIPT ${Date.now()}`;
let prisma: PrismaClient, companyId = "", customerId = "", productId = ""; const orderIds: string[] = [], accountIds: string[] = [];
async function makeAccount(value: string, index: number) { const order = await prisma.productionOrder.create({ data: { number: `${marker}-${index}`, entryDate: new Date("2026-09-01T00:00:00Z"), companyId, customerId, productId, quantity: 1, unitPrice: value } }); orderIds.push(order.id); const billing = await prisma.billing.create({ data: { productionOrderId: order.id, companyId, invoiceNumber: `${marker}-NF-${index}`, issueDate: new Date("2026-09-01T00:00:00Z"), amount: value, competenceDate: new Date("2026-09-01T00:00:00Z"), notes: marker } }); const account = await prisma.accountReceivable.create({ data: { companyId, customerId, billingId: billing.id, description: marker, competenceDate: billing.competenceDate, dueDate: new Date("2099-12-31T00:00:00Z"), originalAmount: value } }); accountIds.push(account.id); return account.id; }
describe.runIf(run)("recebimentos no PostgreSQL real", () => {
  beforeAll(async () => { prisma = (await import("@/lib/prisma")).prisma; companyId = (await prisma.company.create({ data: { name: marker } })).id; customerId = (await prisma.customer.create({ data: { name: marker } })).id; productId = (await prisma.product.create({ data: { name: marker } })).id; await makeAccount("8000", 1); await makeAccount("7000", 2); await makeAccount("10000", 3); await makeAccount("10000", 4); await makeAccount("100", 5); await makeAccount("100", 6); });
  afterAll(async () => { if (companyId) { await prisma.receiptAllocation.deleteMany({ where: { accountReceivableId: { in: accountIds } } }); await prisma.receipt.deleteMany({ where: { companyId, notes: marker } }); await prisma.accountReceivable.deleteMany({ where: { id: { in: accountIds } } }); await prisma.billing.deleteMany({ where: { productionOrderId: { in: orderIds } } }); await prisma.productionOrder.deleteMany({ where: { id: { in: orderIds } } }); await prisma.product.delete({ where: { id: productId } }); await prisma.customer.delete({ where: { id: customerId } }); await prisma.company.delete({ where: { id: companyId } }); } });
  it("registra uma entrada de 25.000 alocada em três NFes", async () => { const receipt = await createReceipt(prisma, { companyId, customerId, receiptDate: new Date(), amount: "25000", notes: marker, allocations: [{ accountReceivableId: accountIds[0], amount: "8000" }, { accountReceivableId: accountIds[1], amount: "7000" }, { accountReceivableId: accountIds[2], amount: "10000" }] }); expect(receipt.allocations).toHaveLength(3); expect(await prisma.receipt.count({ where: { id: receipt.id } })).toBe(1); for (const id of accountIds.slice(0, 3)) { const account = await prisma.accountReceivable.findUniqueOrThrow({ where: { id }, include: { allocations: true } }); expect(receivableStatus(account.originalAmount, account.dueDate, account.allocations)).toBe("Recebida"); } });
  it("registra parcial 4.000, quita com 6.000 e rejeita valor extra", async () => { const id = accountIds[3]; await createReceipt(prisma, { companyId, customerId, receiptDate: new Date(), amount: "4000", notes: marker, allocations: [{ accountReceivableId: id, amount: "4000" }] }); let account = await prisma.accountReceivable.findUniqueOrThrow({ where: { id }, include: { allocations: true } }); expect(receivedAmount(account.allocations).toFixed(4)).toBe("4000.0000"); expect(receivableRemainingAmount(account.originalAmount, account.allocations).toFixed(4)).toBe("6000.0000"); expect(receivableStatus(account.originalAmount, account.dueDate, account.allocations)).toBe("Parcial"); await createReceipt(prisma, { companyId, customerId, receiptDate: new Date(), amount: "6000", notes: marker, allocations: [{ accountReceivableId: id, amount: "6000" }] }); account = await prisma.accountReceivable.findUniqueOrThrow({ where: { id }, include: { allocations: true } }); expect(receivableStatus(account.originalAmount, account.dueDate, account.allocations)).toBe("Recebida"); await expect(createReceipt(prisma, { companyId, customerId, receiptDate: new Date(), amount: "1", notes: marker, allocations: [{ accountReceivableId: id, amount: "1" }] })).rejects.toThrow("saldo atual"); });
  it("rejeita soma inválida sem persistir Receipt", async () => { const before = await prisma.receipt.count({ where: { companyId, notes: marker } }); await expect(createReceipt(prisma, { companyId, customerId, receiptDate: new Date(), amount: "100", notes: marker, allocations: [{ accountReceivableId: accountIds[5], amount: "99" }] })).rejects.toThrow("igual ao valor recebido"); expect(await prisma.receipt.count({ where: { companyId, notes: marker } })).toBe(before); });
  it("serializa duas alocações concorrentes do mesmo saldo", async () => { const id = accountIds[4], request = () => createReceipt(prisma, { companyId, customerId, receiptDate: new Date(), amount: "100", notes: marker, allocations: [{ accountReceivableId: id, amount: "100" }] }); const results = await Promise.allSettled([request(), request()]); expect(results.filter(x => x.status === "fulfilled")).toHaveLength(1); expect(results.filter(x => x.status === "rejected")).toHaveLength(1); const account = await prisma.accountReceivable.findUniqueOrThrow({ where: { id }, include: { allocations: true } }); expect(receivedAmount(account.allocations).toFixed(4)).toBe("100.0000"); expect(receivableRemainingAmount(account.originalAmount, account.allocations).toFixed(4)).toBe("0.0000"); });
});
