import Link from "next/link";
import { PageHeader } from "@/components/page-header";
import { formatCurrency, fortalezaMonthYear } from "@/lib/format";
import { prisma } from "@/lib/prisma";
import { annualBudgetComparison, annualLineKeys } from "@/modules/budget/annual";

type Params={companyId?:string;year?:string;view?:string};
const months=["Jan","Fev","Mar","Abr","Mai","Jun","Jul","Ago","Set","Out","Nov","Dez"];
const labels={grossRevenue:"Receita Bruta",variableExpenses:"(-) Custos e Despesas Variáveis",contributionMargin:"(=) Margem de Contribuição",fixedExpenses:"(-) Custos e Despesas Fixas",operatingProfit:"(=) Lucro Operacional",financialRevenue:"(+) Receitas Financeiras",financialExpenses:"(-) Despesas Financeiras",resultBeforeTaxes:"(=) Resultado Antes dos Tributos",incomeTaxExpenses:"(-) Tributos sobre o Resultado",managerialNetIncome:"(=) Resultado Líquido Gerencial"};
const views={planned:"Previsto",actual:"Realizado",variance:"Variação"} as const;
const statusLabels={DRAFT:"Rascunho",APPROVED:"Aprovado",CLOSED:"Fechado"};
function value(row:{budgeted:unknown;actual:unknown;variance:unknown},view:keyof typeof views){return row[view==="planned"?"budgeted":view] as Parameters<typeof formatCurrency>[0]}
function pct(value:{toFixed(n:number):string}|null){return value?`${value.toFixed(1).replace(".",",")}%`:"—"}

export default async function Page({searchParams}:{searchParams:Promise<Params>}){
 const p=await searchParams,year=Number(p.year)>=1900?Number(p.year):fortalezaMonthYear().year,view=p.view&&p.view in views?p.view as keyof typeof views:"planned";
 const companies=await prisma.company.findMany({orderBy:{name:"asc"}}),active=companies.filter(x=>x.active),companyId=p.companyId||(active.length===1?active[0].id:"");const selected=companies.find(x=>x.id===companyId),data=selected?await annualBudgetComparison(companyId,year):null;
 const query=(next:keyof typeof views)=>`?companyId=${encodeURIComponent(companyId)}&year=${year}&view=${next}`;
 return <><PageHeader title="Previsto x Realizado Anual" description="Doze competências e total anual, sem consolidar empresas." action={{label:"Visão mensal",href:`/financeiro/previsto-realizado?companyId=${companyId}&year=${year}`}}/>
 <form className="panel mb-5 form-grid"><input type="hidden" name="view" value={view}/><label className="field">Empresa<select name="companyId" required defaultValue={companyId}><option value="" disabled>Selecione</option>{companies.map(x=><option key={x.id} value={x.id}>{x.tradeName||x.name}</option>)}</select></label><label className="field">Ano<input name="year" type="number" min="1900" defaultValue={year}/></label><div className="flex items-end"><button className="button-primary">Consultar</button></div></form>
 {!data?<section className="panel"><p className="empty-state">Selecione uma empresa.</p></section>:<><nav className="mb-4 flex gap-2" aria-label="Modo de comparação">{Object.entries(views).map(([key,label])=><Link className={view===key?"button-primary":"button-secondary"} href={query(key as keyof typeof views)} key={key}>{label}</Link>)}</nav>
 <section className="panel mb-5"><div className="table-wrap"><table><thead><tr><th>Linha</th>{months.map(x=><th key={x}>{x}</th>)}<th>Total Ano</th></tr></thead><tbody><tr><td className="font-medium">Status do orçamento</td>{data.budgetStatuses.map((status,i)=><td className="whitespace-nowrap text-xs" key={i}>{status?statusLabels[status]:"Sem orçamento"}</td>)}<td>—</td></tr>{annualLineKeys.map(key=><tr key={key}><td className="min-w-52 font-medium">{labels[key]}</td>{data.lines[key].months.map((row,i)=><td className="whitespace-nowrap" key={i}>{formatCurrency(value(row,view))}</td>)}<td className="whitespace-nowrap font-semibold">{formatCurrency(value(data.lines[key].total,view))}</td></tr>)}</tbody></table></div><p className="mt-4 text-sm text-slate-500">Meses sem orçamento usam Previsto zero. Total anual é a soma das 12 competências; percentuais são calculados sobre os totais, nunca pela média mensal.</p></section>
 <section className="panel mb-5"><h2 className="section-title mb-4">Margens anuais sobre os totais</h2><div className="grid gap-3 md:grid-cols-3"><div>Margem de Contribuição<p>Previsto {pct(data.margins.plannedContribution)} · Realizado {pct(data.margins.actualContribution)}</p></div><div>Margem Operacional<p>Previsto {pct(data.margins.plannedOperating)} · Realizado {pct(data.margins.actualOperating)}</p></div><div>Margem Líquida<p>Previsto {pct(data.margins.plannedNet)} · Realizado {pct(data.margins.actualNet)}</p></div></div></section>
 <section className="panel"><h2 className="section-title mb-4">Totais anuais por classificação</h2>{data.details.length?<div className="table-wrap"><table><thead><tr><th>Classificação</th><th>Grupo</th><th>Previsto</th><th>Realizado</th><th>Variação</th><th>%</th><th>Avaliação</th></tr></thead><tbody>{data.details.map(x=><tr key={x.code}><td>{x.name}<span className="block text-xs text-slate-500">{x.code}</span></td><td>{x.group}</td><td>{formatCurrency(x.budgeted)}</td><td>{formatCurrency(x.actual)}</td><td>{formatCurrency(x.variance)}</td><td>{pct(x.variancePercentage)}</td><td>{x.evaluation}</td></tr>)}</tbody></table></div>:<p className="empty-state">Nenhuma classificação prevista ou realizada no ano.</p>}</section></>}</>;
}
