"use client";
import { useMemo, useState } from "react";
import { SubmitButton } from "./submit-button";
import { FormSection } from "./ui/form-section";
type Account = { id: string; op: string; invoice: string; dueDate: string; original: string; received: string; remaining: string };
function decimal(value: string) { const normalized = value.trim().replace(/\s/g, "").replace(/^R\$/, "").replace(/\.(?=\d{3}(?:\D|$))/g, "").replace(",", "."); return /^\d+(\.\d{1,4})?$/.test(normalized) ? Number(normalized) : 0; }
function money(value: number) { return value.toLocaleString("pt-BR", { style: "currency", currency: "BRL" }); }
export function ReceiptForm({ action, companyId, customerId, accounts, today }: { action: (data: FormData) => void | Promise<void>; companyId: string; customerId: string; accounts: Account[]; today: string }) {
  const [amount, setAmount] = useState(""), [allocations, setAllocations] = useState<Record<string, string>>({});
  const total = useMemo(() => Object.values(allocations).reduce((sum, value) => sum + decimal(value), 0), [allocations]); const difference = decimal(amount) - total;
  return <form action={action} className="space-y-5"><input name="companyId" type="hidden" value={companyId}/><input name="customerId" type="hidden" value={customerId}/>
    <FormSection title="1. Dados do recebimento" description="Informe a data e o valor total que entrou no caixa.">
      <div className="form-grid"><label className="field">Data do recebimento<input defaultValue={today} name="receiptDate" required type="date"/></label><label className="field">Valor recebido<input inputMode="decimal" name="amount" onChange={event => setAmount(event.target.value)} placeholder="0,00" required value={amount}/></label><label className="field sm:col-span-2">Observações<textarea maxLength={2000} name="notes" rows={3}/></label></div>
    </FormSection>
    <section className="panel"><h2 className="section-title mb-4">2. Contas disponíveis e alocações</h2><div className="finance-card-list">{accounts.map(account => { const value = allocations[account.id] || ""; return <article className={`finance-list-card ${value ? "selected" : ""}`} key={account.id}><label className="finance-check-row"><input aria-label={`Selecionar conta ${account.invoice}`} checked={Boolean(value)} onChange={event => setAllocations(current => ({ ...current, [account.id]: event.target.checked ? (accounts.length === 1 ? amount : account.remaining.replace(".", ",")) : "" }))} type="checkbox"/><strong>NFe {account.invoice}</strong></label><p>OP {account.op} • Vence {account.dueDate}</p><dl className="finance-facts"><div><dt>Original</dt><dd>{money(Number(account.original))}</dd></div><div><dt>Recebido</dt><dd>{money(Number(account.received))}</dd></div><div><dt>Saldo</dt><dd>{money(Number(account.remaining))}</dd></div></dl><label className="field">Alocar agora<input disabled={!value} inputMode="decimal" max={account.remaining} name={`allocation-${account.id}`} onChange={event => setAllocations(current => ({ ...current, [account.id]: event.target.value }))} value={value}/></label></article>; })}</div><div className="finance-table-desktop table-wrap"><table><thead><tr><th>Selecionar</th><th>OP</th><th>NFe</th><th>Vencimento</th><th>Original</th><th>Já recebido</th><th>Saldo</th><th>Alocar agora</th></tr></thead><tbody>{accounts.map(account => { const value = allocations[account.id] || ""; return <tr key={account.id}><td><input aria-label={`Selecionar conta ${account.invoice}`} checked={Boolean(value)} onChange={event => setAllocations(current => ({ ...current, [account.id]: event.target.checked ? (accounts.length === 1 ? amount : account.remaining.replace(".", ",")) : "" }))} type="checkbox"/></td><td>{account.op}</td><td>{account.invoice}</td><td>{account.dueDate}</td><td>{money(Number(account.original))}</td><td>{money(Number(account.received))}</td><td>{money(Number(account.remaining))}</td><td><input disabled={!value} inputMode="decimal" max={account.remaining} name={`allocation-${account.id}`} onChange={event => setAllocations(current => ({ ...current, [account.id]: event.target.value }))} value={value}/></td></tr>; })}</tbody></table></div><dl className="detail-grid mt-5"><div><dt>Valor recebido</dt><dd>{money(decimal(amount))}</dd></div><div><dt>Total alocado</dt><dd>{money(total)}</dd></div><div><dt>Saldo não alocado</dt><dd>{money(difference)}</dd></div></dl><div className="mt-5"><SubmitButton disabled={!amount || total <= 0 || Math.abs(difference) > 0.00001}>Registrar recebimento</SubmitButton></div></section></form>;
}
