import { afterAll, beforeAll, describe, expect, it } from "vitest";
import type { PrismaClient } from "@/generated/prisma";
import { createPayment } from "@/modules/accounts-payable/payments";
import { createReceipt } from "@/modules/receipts/creation";
import { flowTotals } from "./domain";
const run = process.env.RUN_CASH_FLOW_INTEGRATION === "1", marker = `TEMP QA CASH ${Date.now()}`;
let prisma: PrismaClient, companyId = "", customerId = "", productId = "", contractorId = "", payableId = ""; const orderIds: string[] = [], receivableIds: string[] = [];
let cashFlowData: typeof import("./queries").cashFlowData;
async function receivable(value: string, index: number, due = "2026-09-15") { const order = await prisma.productionOrder.create({ data: { number: `${marker}-${index}`, entryDate: new Date("2026-09-01T00:00:00Z"), companyId, customerId, productId, quantity: 1, unitPrice: value } }); orderIds.push(order.id); const billing = await prisma.billing.create({ data: { productionOrderId: order.id, companyId, invoiceNumber: `${marker}-NF-${index}`, issueDate: new Date("2025-01-01T00:00:00Z"), competenceDate: new Date("2025-01-01T00:00:00Z"), amount: value, notes: marker } }); const account = await prisma.accountReceivable.create({ data: { companyId, customerId, billingId: billing.id, description: marker, competenceDate: billing.competenceDate, dueDate: new Date(`${due}T00:00:00Z`), originalAmount: value } }); receivableIds.push(account.id); return account.id; }
describe.runIf(run)("fluxo de caixa no PostgreSQL real", () => {
  beforeAll(async () => { cashFlowData = (await import("./queries")).cashFlowData; });
  beforeAll(async () => { prisma = (await import("@/lib/prisma")).prisma; companyId = (await prisma.company.create({ data: { name: marker } })).id; customerId = (await prisma.customer.create({ data: { name: marker } })).id; productId = (await prisma.product.create({ data: { name: marker } })).id; contractorId = (await prisma.contractor.create({ data: { name: marker } })).id; const ar = await receivable("10000", 1); const settlement = await prisma.contractorSettlement.create({ data: { companyId, contractorId, periodYear: 2026, periodMonth: 9, status: "APPROVED", notes: marker } }); payableId = (await prisma.accountPayable.create({ data: { companyId, contractorSettlementId: settlement.id, description: marker, competenceDate: new Date("2026-09-01T00:00:00Z"), dueDate: new Date("2026-09-15T00:00:00Z"), originalAmount: "784" } })).id; await createReceipt(prisma, { companyId, customerId, receiptDate: new Date("2026-09-08T00:00:00Z"), amount: "4000", notes: marker, allocations: [{ accountReceivableId: ar, amount: "4000" }] }); await createPayment(prisma, payableId, { paymentDate: new Date("2026-09-08T00:00:00Z"), amount: "500", notes: marker }); });
  afterAll(async () => { if (companyId) { await prisma.receiptAllocation.deleteMany({ where: { accountReceivableId: { in: receivableIds } } }); await prisma.receipt.deleteMany({ where: { companyId, notes: marker } }); await prisma.payment.deleteMany({ where: { accountPayableId: payableId } }); await prisma.accountPayable.deleteMany({ where: { companyId } }); await prisma.contractorSettlement.deleteMany({ where: { companyId } }); await prisma.accountReceivable.deleteMany({ where: { id: { in: receivableIds } } }); await prisma.billing.deleteMany({ where: { productionOrderId: { in: orderIds } } }); await prisma.productionOrder.deleteMany({ where: { id: { in: orderIds } } }); await prisma.contractor.delete({ where: { id: contractorId } }); await prisma.product.delete({ where: { id: productId } }); await prisma.customer.delete({ where: { id: customerId } }); await prisma.company.delete({ where: { id: companyId } }); } });
  it("deriva realizado 4.000 - 500 = 3.500 e previsto 6.000 - 284 = 5.716", async () => { const range = { companyId, from: new Date("2026-09-01T00:00:00Z"), to: new Date("2026-09-30T00:00:00Z") }; const actual = flowTotals((await cashFlowData({ ...range, view: "actual" })).movements); expect(actual.entries.toFixed(2)).toBe("4000.00"); expect(actual.exits.toFixed(2)).toBe("500.00"); expect(actual.net.toFixed(2)).toBe("3500.00"); const predicted = flowTotals((await cashFlowData({ ...range, view: "predicted" })).movements); expect(predicted.entries.toFixed(2)).toBe("6000.00"); expect(predicted.exits.toFixed(2)).toBe("284.00"); expect(predicted.net.toFixed(2)).toBe("5716.00"); });
  it("conta Receipt multi-NFe uma única vez e ignora competência", async () => { const ids = [await receivable("8000", 2, "2027-01-01"), await receivable("7000", 3, "2027-01-01"), await receivable("10000", 4, "2027-01-01")]; await createReceipt(prisma, { companyId, customerId, receiptDate: new Date("2026-10-08T00:00:00Z"), amount: "25000", notes: marker, allocations: ids.map((id, index) => ({ accountReceivableId: id, amount: ["8000", "7000", "10000"][index] })) }); const data = await cashFlowData({ companyId, from: new Date("2026-10-01T00:00:00Z"), to: new Date("2026-10-31T00:00:00Z"), view: "actual" }); const entries = data.movements.filter(x => x.direction === "IN"); expect(entries).toHaveLength(1); expect(entries[0].amount.toFixed(2)).toBe("25000.00"); });
});
