import { afterAll, beforeAll, describe, expect, it } from "vitest";
import { prisma } from "@/lib/prisma";
import { addClassificationEntry, addGrossRevenue, copyBudget, createBudget } from "./service";
import { annualBudgetComparison } from "./annual";

const suite=process.env.RUN_DATABASE_TESTS==="1"?describe:describe.skip;
const marker="TEMP QA COPY BUDGET";let companyId="",sourceId="",salaryId="",energyId="";
async function cleanup(){const companies=await prisma.company.findMany({where:{name:{startsWith:marker}},select:{id:true}}),ids=companies.map(x=>x.id);if(ids.length){await prisma.budgetEntry.deleteMany({where:{budget:{companyId:{in:ids}}}});await prisma.budget.deleteMany({where:{companyId:{in:ids}}});await prisma.company.deleteMany({where:{id:{in:ids}}});}await prisma.financialClassification.deleteMany({where:{code:{startsWith:"TEMP_QA_COPY_BUDGET"}}});}
suite("cópia de orçamento no PostgreSQL",()=>{
 beforeAll(async()=>{await cleanup();companyId=(await prisma.company.create({data:{name:marker}})).id;const rows=await Promise.all([prisma.financialClassification.create({data:{code:"TEMP_QA_COPY_BUDGET_SALARY",name:"Salários antigos",financialNature:"OPERATING_EXPENSE",dreGroup:"FIXED_COST_EXPENSE"}}),prisma.financialClassification.create({data:{code:"TEMP_QA_COPY_BUDGET_ENERGY",name:"Energia",financialNature:"OPERATING_EXPENSE",dreGroup:"FIXED_COST_EXPENSE"}})]);salaryId=rows[0].id;energyId=rows[1].id;sourceId=(await createBudget(prisma,companyId,2026,1,"Não copiar esta observação")).id;await addGrossRevenue(prisma,sourceId,"100000","Receita");await addClassificationEntry(prisma,sourceId,salaryId,"30000","Folha");await addClassificationEntry(prisma,sourceId,energyId,"5000","Energia");});
 afterAll(async()=>{await cleanup();await prisma.$disconnect();});
 it("copia planejamento com snapshots atuais, sem fatos",async()=>{await prisma.financialClassification.update({where:{id:salaryId},data:{name:"Salários atuais"}});const copied=await copyBudget(prisma,sourceId,2026,2);expect(copied.notes).toBeNull();expect(copied.entries).toHaveLength(3);expect(copied.entries.find(x=>x.classificationId===salaryId)?.classificationNameSnapshot).toBe("Salários atuais");expect(await prisma.billing.count({where:{companyId}})).toBe(0);expect(await prisma.accountPayable.count({where:{companyId}})).toBe(0);});
 it("não sobrescreve destino existente",async()=>{await expect(copyBudget(prisma,sourceId,2026,2)).rejects.toThrow("Já existe");expect(await prisma.budget.count({where:{companyId,competenceDate:new Date("2026-02-01T00:00:00Z")}})).toBe(1);});
 it("agrega o ano, preserva meses vazios e isola outro ano",async()=>{const annual=await annualBudgetComparison(companyId,2026);expect(annual.lines.grossRevenue.total.budgeted.toFixed(2)).toBe("200000.00");expect(annual.lines.grossRevenue.months[2].budgeted.isZero()).toBe(true);expect((await annualBudgetComparison(companyId,2025)).lines.grossRevenue.total.budgeted.isZero()).toBe(true);});
 it("rejeita atomicamente classificação inativa",async()=>{await prisma.financialClassification.update({where:{id:energyId},data:{active:false}});await expect(copyBudget(prisma,sourceId,2026,3)).rejects.toThrow("inativas ou inelegíveis");expect(await prisma.budget.count({where:{companyId,competenceDate:new Date("2026-03-01T00:00:00Z")}})).toBe(0);await prisma.financialClassification.update({where:{id:energyId},data:{active:true}});});
 it("não perpetua classificação que se tornou NON_DRE",async()=>{await prisma.financialClassification.update({where:{id:energyId},data:{financialNature:"NON_DRE",dreGroup:null}});await expect(copyBudget(prisma,sourceId,2026,5)).rejects.toThrow("inativas ou inelegíveis");expect(await prisma.budget.count({where:{companyId,competenceDate:new Date("2026-05-01T00:00:00Z")}})).toBe(0);await prisma.financialClassification.update({where:{id:energyId},data:{financialNature:"OPERATING_EXPENSE",dreGroup:"FIXED_COST_EXPENSE"}});});
 it("permite apenas uma cópia concorrente para o mesmo destino",async()=>{const results=await Promise.allSettled([copyBudget(prisma,sourceId,2026,4),copyBudget(prisma,sourceId,2026,4)]);expect(results.filter(x=>x.status==="fulfilled")).toHaveLength(1);expect(results.filter(x=>x.status==="rejected")).toHaveLength(1);expect(await prisma.budget.count({where:{companyId,competenceDate:new Date("2026-04-01T00:00:00Z")}})).toBe(1);});
});
