import { afterAll, beforeAll, describe, expect, it } from "vitest";
import { prisma } from "@/lib/prisma";
import { addClassificationEntry, addGrossRevenue, approveBudget, closeBudget, copyBudget, createBudget, deleteBudgetEntry, updateBudgetEntry, updateBudgetNotes } from "./service";

const suite=process.env.RUN_DATABASE_TESTS==="1"?describe:describe.skip;
const marker="TEMP QA GOVERNANCE BUDGET";let companyId="",classificationId="";
async function cleanup(){const companies=await prisma.company.findMany({where:{name:{startsWith:marker}},select:{id:true}}),ids=companies.map(x=>x.id);if(ids.length){await prisma.budgetEntry.deleteMany({where:{budget:{companyId:{in:ids}}}});await prisma.budget.deleteMany({where:{companyId:{in:ids}}});await prisma.company.deleteMany({where:{id:{in:ids}}});}await prisma.financialClassification.deleteMany({where:{code:{startsWith:"TEMP_QA_GOVERNANCE"}}});}
suite("governança do orçamento no PostgreSQL",()=>{
 beforeAll(async()=>{await cleanup();companyId=(await prisma.company.create({data:{name:marker}})).id;classificationId=(await prisma.financialClassification.create({data:{code:"TEMP_QA_GOVERNANCE_SALARY",name:"Salários TEMP",financialNature:"OPERATING_EXPENSE",dreGroup:"FIXED_COST_EXPENSE"}})).id;});
 afterAll(async()=>{await cleanup();await prisma.$disconnect();});
 it("novo Budget nasce DRAFT, é editável e vazio não aprova",async()=>{const budget=await createBudget(prisma,companyId,2027,1,"Inicial");expect(budget.status).toBe("DRAFT");expect(budget.approvedAt).toBeNull();expect(budget.closedAt).toBeNull();await updateBudgetNotes(prisma,budget.id,"Editado");await expect(approveBudget(prisma,budget.id)).rejects.toThrow("sem linhas");});
 it("aprova DRAFT com linha, congela e preserva o previsto",async()=>{const budget=await createBudget(prisma,companyId,2027,2);const revenue=await addGrossRevenue(prisma,budget.id,"100000");await addClassificationEntry(prisma,budget.id,classificationId,"20000");const approved=await approveBudget(prisma,budget.id);expect(approved.status).toBe("APPROVED");expect(approved.approvedAt).not.toBeNull();await expect(updateBudgetNotes(prisma,budget.id,"Não")).rejects.toThrow("Rascunho");await expect(updateBudgetEntry(prisma,revenue.id,"1")).rejects.toThrow("Rascunho");await expect(deleteBudgetEntry(prisma,revenue.id)).rejects.toThrow("Rascunho");await expect(addGrossRevenue(prisma,budget.id,"1")).rejects.toThrow("Rascunho");await expect(approveBudget(prisma,budget.id)).rejects.toThrow("Rascunho");expect((await prisma.budgetEntry.findUniqueOrThrow({where:{id:revenue.id}})).amount.toFixed(0)).toBe("100000");});
 it("fecha APPROVED e CLOSED rejeita todas as transições/mutações",async()=>{const budget=await prisma.budget.findUniqueOrThrow({where:{companyId_competenceDate:{companyId,competenceDate:new Date("2027-02-01T00:00:00Z")}},include:{entries:true}});const closed=await closeBudget(prisma,budget.id);expect(closed.status).toBe("CLOSED");expect(closed.approvedAt).not.toBeNull();expect(closed.closedAt).not.toBeNull();await expect(closeBudget(prisma,budget.id)).rejects.toThrow("Aprovado");await expect(approveBudget(prisma,budget.id)).rejects.toThrow("Rascunho");await expect(updateBudgetNotes(prisma,budget.id,"Não")).rejects.toThrow("Rascunho");await expect(updateBudgetEntry(prisma,budget.entries[0].id,"1")).rejects.toThrow("Rascunho");await expect(deleteBudgetEntry(prisma,budget.entries[0].id)).rejects.toThrow("Rascunho");await expect(addClassificationEntry(prisma,budget.id,classificationId,"1")).rejects.toThrow("Rascunho");});
 it("cópias de CLOSED e APPROVED sempre nascem DRAFT",async()=>{const closed=await prisma.budget.findUniqueOrThrow({where:{companyId_competenceDate:{companyId,competenceDate:new Date("2027-02-01T00:00:00Z")}}});const fromClosed=await copyBudget(prisma,closed.id,2027,3);expect(fromClosed.status).toBe("DRAFT");expect(fromClosed.approvedAt).toBeNull();expect(fromClosed.closedAt).toBeNull();const approvedSource=await createBudget(prisma,companyId,2027,4);await addGrossRevenue(prisma,approvedSource.id,"10");await approveBudget(prisma,approvedSource.id);expect((await copyBudget(prisma,approvedSource.id,2027,5)).status).toBe("DRAFT");});
 it("serializa duas aprovações concorrentes",async()=>{const budget=await createBudget(prisma,companyId,2027,6);await addGrossRevenue(prisma,budget.id,"10");const results=await Promise.allSettled([approveBudget(prisma,budget.id),approveBudget(prisma,budget.id)]);expect(results.filter(x=>x.status==="fulfilled")).toHaveLength(1);expect(results.filter(x=>x.status==="rejected")).toHaveLength(1);const final=await prisma.budget.findUniqueOrThrow({where:{id:budget.id}});expect(final.status).toBe("APPROVED");expect(final.approvedAt).not.toBeNull();expect(final.closedAt).toBeNull();});
 it("serializa edição concorrente com aprovação sem editar depois do congelamento",async()=>{const budget=await createBudget(prisma,companyId,2027,7);const entry=await addGrossRevenue(prisma,budget.id,"100");const [edit,approval]=await Promise.allSettled([updateBudgetEntry(prisma,entry.id,"200"),approveBudget(prisma,budget.id)]);expect(approval.status).toBe("fulfilled");const finalBudget=await prisma.budget.findUniqueOrThrow({where:{id:budget.id}}),finalEntry=await prisma.budgetEntry.findUniqueOrThrow({where:{id:entry.id}});expect(finalBudget.status).toBe("APPROVED");if(edit.status==="fulfilled")expect(finalEntry.amount.toFixed(0)).toBe("200");else expect(finalEntry.amount.toFixed(0)).toBe("100");});
});
