import { Feedback } from "@/components/feedback";
import { PageHeader } from "@/components/page-header";
import { SubmitButton } from "@/components/submit-button";
import { formatCurrency, fortalezaMonthYear } from "@/lib/format";
import { prisma } from "@/lib/prisma";
import { currentUser } from "@/modules/auth/session";
import { addClassificationAction, addRevenueAction, approveBudgetAction, closeBudgetAction, copyBudgetAction, createBudgetAction, deleteEntryAction, updateBudgetAction, updateEntryAction } from "@/modules/budget/actions";
import { budgetComparison } from "@/modules/budget/queries";

type Params={companyId?:string;month?:string;year?:string;success?:string;error?:string};
const months=["Janeiro","Fevereiro","Março","Abril","Maio","Junho","Julho","Agosto","Setembro","Outubro","Novembro","Dezembro"];
const labels={grossRevenue:"Receita Bruta",variableExpenses:"(-) Custos e Despesas Variáveis",contributionMargin:"(=) Margem de Contribuição",fixedExpenses:"(-) Custos e Despesas Fixas",operatingProfit:"(=) Lucro Operacional",financialRevenue:"(+) Receitas Financeiras",financialExpenses:"(-) Despesas Financeiras",resultBeforeTaxes:"(=) Resultado Antes dos Tributos",incomeTaxExpenses:"(-) Tributos sobre o Resultado",managerialNetIncome:"(=) Resultado Líquido Gerencial"};
const statusLabels={DRAFT:"Rascunho",APPROVED:"Aprovado",CLOSED:"Fechado"};
function pct(v:{toFixed(n:number):string}|null){return v?`${v.toFixed(1).replace(".",",")}%`:"—"}
function date(v:Date|null){return v?v.toLocaleString("pt-BR",{timeZone:"America/Fortaleza"}):"—"}
function Hidden({companyId,month,year}:{companyId:string;month:number;year:number}){return <><input type="hidden" name="companyId" value={companyId}/><input type="hidden" name="month" value={month}/><input type="hidden" name="year" value={year}/></>}

export default async function Page({searchParams}:{searchParams:Promise<Params>}){
 const [p,user]=await Promise.all([searchParams,currentUser()]),canManage=user?.role==="ADMIN"||user?.role==="FINANCE",current=fortalezaMonthYear(),month=Number(p.month)>=1&&Number(p.month)<=12?Number(p.month):current.month,year=Number(p.year)>=1900?Number(p.year):current.year;
 const companies=await prisma.company.findMany({orderBy:{name:"asc"}}),active=companies.filter(x=>x.active),companyId=p.companyId||(active.length===1?active[0].id:"");
 const selected=companies.find(x=>x.id===companyId),data=selected?await budgetComparison(companyId,year,month):null,budget=data?.budget;
 const used=new Set(budget?.entries.map(x=>x.classificationId).filter(Boolean));
 const classifications=budget?.status==="DRAFT"?await prisma.financialClassification.findMany({where:{active:true,financialNature:{in:["OPERATING_EXPENSE","DRE_POST_OPERATING"]},id:{notIn:[...used] as string[]}},orderBy:{name:"asc"}}):[];
 return <><PageHeader title="Previsto x Realizado" description="Orçamento mensal da DRE comparado aos fatos realizados, sem impacto no Fluxo de Caixa." action={{label:"Visão anual",href:`/financeiro/previsto-realizado/anual?companyId=${companyId}&year=${year}`}}/><Feedback success={p.success} error={p.error}/>
 <form className="panel mb-5 form-grid"><label className="field">Empresa<select name="companyId" required defaultValue={companyId}><option value="" disabled>Selecione</option>{companies.map(x=><option key={x.id} value={x.id}>{x.tradeName||x.name}{x.active?"":" (inativa)"}</option>)}</select></label><label className="field">Mês<select name="month" defaultValue={month}>{months.map((x,i)=><option key={x} value={i+1}>{x}</option>)}</select></label><label className="field">Ano<input name="year" type="number" min="1900" defaultValue={year}/></label><div className="flex items-end"><button className="button-primary">Consultar</button></div></form>
 {!data||!selected?<section className="panel"><p className="empty-state">Selecione uma empresa.</p></section>:<>
 {!budget?<section className="panel mb-5"><p className="mb-4">Não há orçamento cadastrado para esta competência. O realizado continua disponível abaixo.</p>{canManage?<form action={createBudgetAction}><Hidden companyId={companyId} month={month} year={year}/><label className="field mb-3">Observações<input name="notes"/></label><SubmitButton>Criar orçamento</SubmitButton></form>:null}</section>:
 <section className="panel mb-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="section-title">Orçamento · {selected.tradeName||selected.name} · {months[month-1]}/{year}</h2><p className="mt-2"><span className="rounded-full bg-slate-100 px-3 py-1 text-sm font-semibold">{statusLabels[budget.status]}</span></p><p className="mt-2 text-sm text-slate-500">Aprovado em: {date(budget.approvedAt)} por {budget.approvedBy?.name||"—"} · Fechado em: {date(budget.closedAt)} por {budget.closedBy?.name||"—"}</p></div>{canManage&&budget.status==="DRAFT"?<form action={approveBudgetAction} className="max-w-md rounded-lg border border-amber-200 bg-amber-50 p-3"><Hidden companyId={companyId} month={month} year={year}/><input type="hidden" name="budgetId" value={budget.id}/><label className="mb-3 flex gap-2 text-sm"><input type="checkbox" required/>Após a aprovação, este orçamento não poderá mais ser editado.</label><SubmitButton>Aprovar orçamento</SubmitButton></form>:canManage&&budget.status==="APPROVED"?<form action={closeBudgetAction} className="max-w-md rounded-lg border border-rose-200 bg-rose-50 p-3"><Hidden companyId={companyId} month={month} year={year}/><input type="hidden" name="budgetId" value={budget.id}/><label className="mb-3 flex gap-2 text-sm"><input type="checkbox" required/>Após o fechamento, este orçamento ficará definitivamente somente leitura nesta versão.</label><SubmitButton>Fechar orçamento</SubmitButton></form>:null}</div>
 {canManage&&budget.status==="DRAFT"&&<><form action={updateBudgetAction} className="mt-4 flex items-end gap-3"><Hidden companyId={companyId} month={month} year={year}/><input type="hidden" name="budgetId" value={budget.id}/><label className="field flex-1">Observações do orçamento<input name="notes" defaultValue={budget.notes||""}/></label><SubmitButton>Salvar observações</SubmitButton></form><div className="mt-4 grid gap-5 lg:grid-cols-2">{!budget.entries.some(x=>x.entryType==="GROSS_REVENUE")&&<form action={addRevenueAction} className="form-grid"><Hidden companyId={companyId} month={month} year={year}/><input type="hidden" name="budgetId" value={budget.id}/><label className="field">Receita Bruta prevista<input name="amount" required placeholder="0,00"/></label><label className="field">Observação<input name="notes"/></label><SubmitButton>Adicionar Receita Bruta</SubmitButton></form>}<form action={addClassificationAction} className="form-grid"><Hidden companyId={companyId} month={month} year={year}/><input type="hidden" name="budgetId" value={budget.id}/><label className="field">Classificação<select name="classificationId" required defaultValue=""><option value="" disabled>Selecione</option>{classifications.map(x=><option key={x.id} value={x.id}>{x.name} · {x.dreGroup}</option>)}</select></label><label className="field">Valor previsto<input name="amount" required placeholder="0,00"/></label><label className="field">Observação<input name="notes"/></label><SubmitButton disabled={!classifications.length}>Adicionar classificação</SubmitButton></form></div></>}
 {canManage?<form action={copyBudgetAction} className="mt-6 rounded-lg bg-slate-50 p-4"><Hidden companyId={companyId} month={month} year={year}/><input type="hidden" name="budgetId" value={budget.id}/><p className="mb-2 font-semibold">Copiar orçamento</p><p className="mb-3 text-sm text-slate-500">A cópia sempre cria um novo Rascunho e não transfere status ou timestamps.</p><div className="form-grid"><label className="field">Mês de destino<input name="destinationMonth" type="number" min="1" max="12" required/></label><label className="field">Ano de destino<input name="destinationYear" type="number" min="1900" defaultValue={year} required/></label><div className="flex items-end"><SubmitButton>Copiar orçamento</SubmitButton></div></div></form>:null}
 <div className="mt-6 grid gap-3">{budget.entries.map(x=>canManage&&budget.status==="DRAFT"?<form action={updateEntryAction} className="grid gap-2 rounded-lg border border-slate-200 p-3 md:grid-cols-[2fr_1fr_2fr_auto_auto]" key={x.id}><Hidden companyId={companyId} month={month} year={year}/><input type="hidden" name="entryId" value={x.id}/><div><strong>{x.entryType==="GROSS_REVENUE"?"Receita Bruta":x.classificationNameSnapshot}</strong><p className="text-xs text-slate-500">{x.classificationCodeSnapshot||"Linha especial"}</p></div><input name="amount" defaultValue={x.amount.toFixed(2).replace(".",",")} required/><input name="notes" defaultValue={x.notes||""}/><SubmitButton>Salvar</SubmitButton><button className="button-secondary" formAction={deleteEntryAction}>Excluir</button></form>:<div className="grid gap-2 rounded-lg border border-slate-200 p-3 md:grid-cols-[2fr_1fr_2fr]" key={x.id}><div><strong>{x.entryType==="GROSS_REVENUE"?"Receita Bruta":x.classificationNameSnapshot}</strong><p className="text-xs text-slate-500">{x.classificationCodeSnapshot||"Linha especial"}</p></div><span>{formatCurrency(x.amount)}</span><span>{x.notes||"—"}</span></div>)}</div></section>}
 <section className="panel mb-5"><h2 className="section-title mb-4">DRE · Previsto x Realizado</h2><div className="table-wrap"><table><thead><tr><th>Linha</th><th>Previsto</th><th>Realizado</th><th>Variação</th><th>%</th><th>Avaliação</th></tr></thead><tbody>{Object.entries(data.headlines).map(([key,row])=><tr key={key}><td>{labels[key as keyof typeof labels]}</td><td>{formatCurrency(row.budgeted)}</td><td>{formatCurrency(row.actual)}</td><td>{formatCurrency(row.variance)}</td><td>{pct(row.variancePercentage)}</td><td>{row.evaluation}</td></tr>)}</tbody></table></div></section>
 <section className="panel"><h2 className="section-title mb-4">Detalhamento por classificação</h2>{data.details.length?<div className="table-wrap"><table><thead><tr><th>Classificação</th><th>Grupo</th><th>Previsto</th><th>Realizado</th><th>Variação</th><th>%</th><th>Avaliação</th></tr></thead><tbody>{data.details.map(x=><tr key={x.code}><td>{x.name}<span className="block text-xs text-slate-500">{x.code}</span></td><td>{x.group}</td><td>{formatCurrency(x.budgeted)}</td><td>{formatCurrency(x.actual)}</td><td>{formatCurrency(x.variance)}</td><td>{pct(x.variancePercentage)}</td><td>{x.evaluation}</td></tr>)}</tbody></table></div>:<p className="empty-state">Nenhuma classificação orçada ou realizada nesta competência.</p>}</section></>}</>;
}
